# Generated by Django 4.2.7 on 2024-02-05 19:57

from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('server_admins', '0002_remove_server_local_filename_and_more'),
        ('api', '0002_alter_rolewebhook_hmac_hash_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminsConfigDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активирован')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('type_of_distribution', models.CharField(choices=[('LOCAL', 'Локальный файл'), ('API', 'Через API'), ('API_LOCAL', 'Локальный файл и API')], default='LOCAL', max_length=10, verbose_name='Вариант распространения конфигурации')),
                ('local_filename', models.CharField(blank=True, max_length=100, null=True, validators=[utils.filename_validator], verbose_name='Название локального файла')),
                ('url', models.CharField(blank=True, max_length=100, null=True, validators=[utils.url_postfix_validator], verbose_name='Постфикс url')),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='server_url', to='server_admins.server', verbose_name='Сервер')),
            ],
            options={
                'verbose_name': 'Доступ к файлу конфигурации',
                'verbose_name_plural': '2. Доступ к файлу конфигурации',
            },
        ),
        migrations.AlterField(
            model_name='rolewebhook',
            name='hmac_hash_type',
            field=models.CharField(blank=True, choices=[('blake2b', 'blake2b'), ('blake2s', 'blake2s'), ('md5', 'md5'), ('md5-sha1', 'md5-sha1'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha3_224', 'sha3_224'), ('sha3_256', 'sha3_256'), ('sha3_384', 'sha3_384'), ('sha3_512', 'sha3_512'), ('sha512', 'sha512'), ('sha512_224', 'sha512_224'), ('sha512_256', 'sha512_256'), ('shake_128', 'shake_128'), ('shake_256', 'shake_256'), ('sm3', 'sm3')], help_text='Обычно предоставляется тем, кто будет вызывать вебхук, например sha256 для Battlemetrics', max_length=64, verbose_name='Тип хеша в HMAC'),
        ),
        migrations.AlterField(
            model_name='rolewebhook',
            name='request_sender',
            field=models.CharField(choices=[('default', 'Стандартный'), ('battlemetrics', 'Battlemetrics.com')], default='default', help_text='Активирует специфичные для каждого сервиса алгоритмы проверки HMAC у запроса', max_length=128, verbose_name='Сервис отправляющий запрос'),
        ),
        migrations.DeleteModel(
            name='ServerUrl',
        ),
    ]
