# Generated by Django 4.2.7 on 2024-02-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_rolewebhook_hmac_hash_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolewebhook',
            name='request_sender',
            field=models.CharField(choices=[('default', 'Стандартный'), ('battlemetrics', 'Battlemetrics.com')], default='default', help_text='Активирует специфичные для каждого сервиса алгоритмы проверки HMAC у запроса', max_length=128, verbose_name='Сервис отправляющий запрос'),
        ),
    ]
