# Generated by Django 4.2.7 on 2024-03-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_adminsconfigdistribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolewebhook',
            name='set_common_date_of_end',
            field=models.BooleanField(default=False, help_text='Если пользователь с переданным steam_id не будет найден - он будет создан', verbose_name='Устанавливать ли общее время до окончания полномочий при создании новых пользователей'),
        ),
        migrations.AlterField(
            model_name='rolewebhook',
            name='duration_until_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стандартно выдаваемая продолжительность полномочий, оставьте пустым для бессрочных полномочий'),
        ),
    ]
