# Generated by Django 4.2.7 on 2024-02-02 13:48

import base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_serverurl_adminsconfigdistribution_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminsconfigdistribution',
            options={'verbose_name': 'Доступ к файлу конфигурации привилегированных пользователей', 'verbose_name_plural': '2. Доступ к файлу конфигурации привилегированных пользователей'},
        ),
        migrations.AddField(
            model_name='adminsconfigdistribution',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='adminsconfigdistribution',
            name='local_filename',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[base.filename_validator], verbose_name='Название локального файла'),
        ),
        migrations.AddField(
            model_name='adminsconfigdistribution',
            name='title',
            field=models.CharField(default='Стандартное имя после миграции со старой версии', max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminsconfigdistribution',
            name='type_of_distribution',
            field=models.CharField(choices=[('LOCAL', 'Локальный файл'), ('API', 'Через API'), ('API_LOCAL', 'Локальный файл и API')], default='LOCAL', max_length=10, verbose_name='Вариант распространения конфигурации'),
        ),
        migrations.AlterField(
            model_name='adminsconfigdistribution',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активирован'),
        ),
        migrations.AlterField(
            model_name='adminsconfigdistribution',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[base.url_postfix_validator], verbose_name='Постфикс url'),
        ),
    ]
