# Generated by Django 4.2.11 on 2024-04-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rolewebhook_set_common_date_of_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminsconfigdistribution',
            options={'verbose_name': 'Распространение конфигурации', 'verbose_name_plural': '2. Распространение конфигураций'},
        ),
        migrations.AlterField(
            model_name='rolewebhook',
            name='duration_until_end',
            field=models.IntegerField(blank=True, help_text='Оставьте пустым для бессрочных полномочий', null=True, verbose_name='Стандартно выдаваемая продолжительность полномочий'),
        ),
    ]
