# Generated by Django 4.2.7 on 2024-02-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_adminsconfigdistribution_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminsconfigdistribution',
            options={'verbose_name': 'Доступ к файлу конфигурации', 'verbose_name_plural': '2. Доступ к файлу конфигурации'},
        ),
    ]
