# Generated by Django 4.2.14 on 2025-06-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_adminsconfigdistribution_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolewebhook',
            name='try_to_increase_existing_record',
            field=models.BooleanField(default=True, help_text='Если активно - сервис попытается найти существующую активную запись в выдачей таких же ролей на таком же сервере и увеличит время в этой записи, если не найдёт - создаст новую, если не активно - будет просто создана новая запись', verbose_name='Попытаться ли увеличить существующую запись?'),
        ),
    ]
