# Generated by Django 4.2.14 on 2025-08-15 21:35

from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('server_admins', '0009_alter_permission_description_alter_permission_title_and_more'),
        ('api', '0006_rolewebhook_try_to_increase_existing_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsconfigdistribution',
            name='description',
            field=models.CharField(blank=True, help_text='Описание', max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='adminsconfigdistribution',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активирована ли это конфигурация распространения', verbose_name='Активирован'),
        ),
        migrations.AlterField(
            model_name='adminsconfigdistribution',
            name='local_filename',
            field=models.CharField(blank=True, help_text='Название локального файла который будет создаваться в соответствующей папке. Доступны латинские буквы, цифры и знак подчеркивания (без множественных знаков подчеркивания подряд)', max_length=100, null=True, validators=[utils.filename_validator], verbose_name='Название локального файла'),
        ),
        migrations.AlterField(
            model_name='adminsconfigdistribution',
            name='server',
            field=models.ForeignKey(help_text='Сервер для которого будет собираться конфигурация привилегированных пользователей', on_delete=django.db.models.deletion.CASCADE, related_name='server_url', to='server_admins.server', verbose_name='Сервер'),
        ),
        migrations.AlterField(
            model_name='adminsconfigdistribution',
            name='title',
            field=models.CharField(help_text='Название конфигурации распространения', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='adminsconfigdistribution',
            name='type_of_distribution',
            field=models.CharField(choices=[('LOCAL', 'Локальный файл'), ('API', 'Через API'), ('API_LOCAL', 'Локальный файл и API')], default='LOCAL', help_text='Выберите какими путями будет распространятся конфигурация, файлом, через API (по ссылке) или комбинированно', max_length=10, verbose_name='Вариант распространения конфигурации'),
        ),
        migrations.AlterField(
            model_name='adminsconfigdistribution',
            name='url',
            field=models.CharField(blank=True, help_text='Часть URL пути до этой конфигурации, просто любой удобный вам текст. Доступны латинские буквы, цифры и знак подчеркивания', max_length=100, null=True, validators=[utils.url_postfix_validator], verbose_name='Постфикс URL'),
        ),
    ]
