# Generated by Django 4.2.4 on 2023-09-01 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Разрешение игрового сервера',
                'verbose_name_plural': '4. Разрешения игрового сервера',
            },
        ),
        migrations.CreateModel(
            name='Privileged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('steam_id', models.BigIntegerField(unique=True, verbose_name='Steam ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активирован')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('date_of_end', models.DateTimeField(blank=True, null=True, verbose_name='Общая дата окончания полномочий')),
            ],
            options={
                'verbose_name': 'Привилегированный пользователь',
                'verbose_name_plural': '2. Привилегированные пользователи',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активирован')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('permissions', models.ManyToManyField(blank=True, to='server_admins.permission', verbose_name='Разрешения')),
            ],
            options={
                'verbose_name': 'Пользовательская роль',
                'verbose_name_plural': '3. Пользовательские роли',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активирован')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('type_of_distribution', models.CharField(choices=[('LOCAL', 'Локальный файл'), ('API', 'Через API'), ('API_LOCAL', 'Локальный файл и API')], default='API', max_length=10, verbose_name='Вариант распространения конфигурации')),
                ('local_filename', models.CharField(blank=True, max_length=100, verbose_name='Название локального файла')),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': '1. Сервера',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='ServerPrivileged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активирована')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('date_of_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания этой роли')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Комментарий')),
                ('privileged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_admins.privileged', verbose_name='Пользователь')),
                ('roles', models.ManyToManyField(to='server_admins.role', verbose_name='Роль')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_admins.server', verbose_name='Сервер')),
            ],
            options={
                'verbose_name': 'Роль на сервере',
                'verbose_name_plural': 'Роли на серверах',
            },
        ),
        migrations.AddField(
            model_name='privileged',
            name='servers_roles',
            field=models.ManyToManyField(blank=True, through='server_admins.ServerPrivileged', to='server_admins.server', verbose_name='Сервера'),
        ),
    ]
