# Generated by Django 4.2.7 on 2024-02-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_admins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='local_filename',
        ),
        migrations.RemoveField(
            model_name='server',
            name='type_of_distribution',
        ),
        migrations.AlterField(
            model_name='server',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
