# Generated by Django 4.2.7 on 2024-02-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_admins', '0002_remove_server_local_filename_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverprivileged',
            options={'verbose_name': 'Роль на сервере', 'verbose_name_plural': '5. Роли пользователей на серверах'},
        ),
        migrations.AlterField(
            model_name='serverprivileged',
            name='date_of_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания роли'),
        ),
    ]
