# Generated by Django 4.2.11 on 2024-04-02 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_admins', '0003_alter_serverprivileged_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Разрешение', 'verbose_name_plural': '4. Разрешения'},
        ),
        migrations.AlterModelOptions(
            name='privileged',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': '2. Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': '3. Роли'},
        ),
    ]
