# Generated by Django 4.2.14 on 2025-06-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_admins', '0005_remove_privileged_servers_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverprivilegedpack',
            name='max_ids',
            field=models.PositiveIntegerField(default=0, help_text='0 если ограничений нет', verbose_name='Максимальное количество ID'),
        ),
    ]
