# Generated by Django 4.2.14 on 2025-06-08 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server_admins', '0006_alter_serverprivilegedpack_max_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverprivilegedpack',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_packs', to=settings.AUTH_USER_MODEL, verbose_name='Модераторы'),
        ),
    ]
