# Generated by Django 4.2.14 on 2025-06-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_admins', '0007_alter_serverprivilegedpack_moderators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverprivileged',
            name='roles',
            field=models.ManyToManyField(related_name='privileged_accesses', to='server_admins.role', verbose_name='Роль'),
        ),
    ]
