# Generated by Django 4.2.14 on 2025-08-15 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server_admins', '0008_alter_serverprivileged_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.CharField(blank=True, help_text='Описание игрового разрешения', max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='title',
            field=models.CharField(help_text='Название игрового разрешения из конфигурации Admins.cfg в Squad', max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='privileged',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата добавления пользователя на сайт', verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='privileged',
            name='date_of_end',
            field=models.DateTimeField(blank=True, help_text="Дата после которой флаг 'Активирован' будет автоматически выключен", null=True, verbose_name='Общая дата окончания полномочий'),
        ),
        migrations.AlterField(
            model_name='privileged',
            name='description',
            field=models.TextField(blank=True, help_text='Описание пользователя', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='privileged',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активирован ли глобально пользователь, если флаг не установлен - пользователь будет убран из конфигурации', verbose_name='Активирован'),
        ),
        migrations.AlterField(
            model_name='privileged',
            name='name',
            field=models.CharField(help_text='Имя привилегированного пользователя', max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='privileged',
            name='steam_id',
            field=models.BigIntegerField(help_text='Steam ID 64', unique=True, verbose_name='Steam ID'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, help_text='Описание роли', max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активирована ли роль, если флаг не установлен - роль будет убрана из всех конфигураций', verbose_name='Активирован'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Набор разрешений который действует для этой роли', to='server_admins.permission', verbose_name='Разрешения'),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(help_text='Название роли', max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='server',
            name='description',
            field=models.CharField(blank=True, help_text='Описание сервера', max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='server',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активирован ли сервер, если флаг не установлен - конфигурация этого сервера будет пустая', verbose_name='Активирован'),
        ),
        migrations.AlterField(
            model_name='server',
            name='title',
            field=models.CharField(help_text='Название сервера', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='serverprivileged',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата добавления роли на сервере', verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='serverprivileged',
            name='date_of_end',
            field=models.DateTimeField(blank=True, help_text="Дата после которой флаг 'Активирован' будет автоматически выключен", null=True, verbose_name='Дата окончания роли'),
        ),
        migrations.AlterField(
            model_name='serverprivileged',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активирована ли данная роль на сервере, если не флаг не установлен - данная роль на сервере будет убрана из конфигурации', verbose_name='Активирована'),
        ),
        migrations.AlterField(
            model_name='serverprivileged',
            name='privileged',
            field=models.ForeignKey(help_text='Привилегированный пользователь которому выдана роль(и) на сервере', on_delete=django.db.models.deletion.CASCADE, related_name='server_accesses', to='server_admins.privileged', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='serverprivileged',
            name='roles',
            field=models.ManyToManyField(help_text='Список ролей', related_name='privileged_accesses', to='server_admins.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='serverprivileged',
            name='server',
            field=models.ForeignKey(help_text='Сервер на котором выдана роль', on_delete=django.db.models.deletion.CASCADE, related_name='privileged_accesses', to='server_admins.server', verbose_name='Сервер'),
        ),
        migrations.AlterField(
            model_name='serverprivilegedpack',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата добавления списка на сайт', verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='serverprivilegedpack',
            name='date_of_end',
            field=models.DateTimeField(blank=True, help_text="Дата после которой флаг 'Активирован' будет автоматически выключен", null=True, verbose_name='Дата окончания действия'),
        ),
        migrations.AlterField(
            model_name='serverprivilegedpack',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активирован ли этот список, если не установлено - список Steam ID будет убран из конфигурации', verbose_name='Активирован'),
        ),
        migrations.AlterField(
            model_name='serverprivilegedpack',
            name='max_ids',
            field=models.PositiveIntegerField(default=0, help_text='Максимальное разрешенное количество SteamID которое можно записать в список. 0 если ограничений нет', verbose_name='Максимальное количество ID'),
        ),
        migrations.AlterField(
            model_name='serverprivilegedpack',
            name='moderators',
            field=models.ManyToManyField(blank=True, help_text='Модераторы которые могут изменять список', related_name='moderated_packs', to=settings.AUTH_USER_MODEL, verbose_name='Модераторы'),
        ),
        migrations.AlterField(
            model_name='serverprivilegedpack',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Список ролей которые будут действовать на серверах', to='server_admins.role', verbose_name='Роли'),
        ),
        migrations.AlterField(
            model_name='serverprivilegedpack',
            name='servers',
            field=models.ManyToManyField(blank=True, help_text='Список серверов на которых будут действовать роли', related_name='privileged_accesses_packs', to='server_admins.server', verbose_name='Сервера'),
        ),
        migrations.AlterField(
            model_name='serverprivilegedpack',
            name='steam_ids',
            field=models.TextField(blank=True, help_text='Список Steam ID через пробел или с новой строки. Поддерживаются комментарии начинающиеся с символа #', verbose_name='Список Steam ID'),
        ),
        migrations.AlterField(
            model_name='serverprivilegedpack',
            name='title',
            field=models.CharField(help_text='Название списка привилегированных пользователей', max_length=200, verbose_name='Название'),
        ),
    ]
