# Generated by Django 4.2.14 on 2025-08-15 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_admins', '0009_alter_permission_description_alter_permission_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverprivilegedpack',
            old_name='moderators',
            new_name='managers',
        ),
    ]
