# Generated by Django 4.2.14 on 2025-08-15 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server_admins', '0010_rename_moderators_serverprivilegedpack_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverprivilegedpack',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='Пользователи которые могут изменять список Steam ID', related_name='managers_packs', to=settings.AUTH_USER_MODEL, verbose_name='Менеджеры'),
        ),
    ]
