# Generated by Django 4.2.4 on 2023-12-12 22:48

import base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server_rotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активирован')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('type_of_distribution', models.CharField(choices=[('LOCAL', 'Локальный файл'), ('API', 'Через API'), ('API_LOCAL', 'Локальный файл и API')], default='LOCAL', max_length=10, verbose_name='Вариант распространения конфигурации')),
                ('local_filename', models.CharField(blank=True, max_length=100, null=True, validators=[base.filename_validator], verbose_name='Название локального файла')),
                ('url', models.CharField(blank=True, max_length=100, null=True, validators=[base.url_postfix_validator], verbose_name='Постфикс url')),
                ('last_update_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего обновления')),
                ('last_queue_number', models.PositiveSmallIntegerField(default=1, verbose_name='Последний номер в очереди')),
                ('rotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='server_rotations.rotation', verbose_name='Ротация')),
            ],
            options={
                'verbose_name': 'распространение ротации',
                'verbose_name_plural': 'распространение ротаций',
                'ordering': ['rotation'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='rotationdistribution',
            constraint=models.UniqueConstraint(condition=models.Q(('local_filename__isnull', False)), fields=('local_filename',), name='distribution_local_filename_unique', violation_error_message='Название локального файла должно быть уникальным'),
        ),
        migrations.AddConstraint(
            model_name='rotationdistribution',
            constraint=models.UniqueConstraint(condition=models.Q(('url__isnull', False)), fields=('url',), name='distribution_url_unique', violation_error_message='Постфикс url должен быть уникальным'),
        ),
    ]
