# Generated by Django 4.2.7 on 2024-02-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_rotations_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotationdistribution',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
