# Generated by Django 4.2.7 on 2024-02-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_rotations_api', '0002_alter_rotationdistribution_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rotationdistribution',
            name='distribution_local_filename_unique',
        ),
        migrations.RemoveConstraint(
            model_name='rotationdistribution',
            name='distribution_url_unique',
        ),
        migrations.AddConstraint(
            model_name='rotationdistribution',
            constraint=models.UniqueConstraint(condition=models.Q(('local_filename__isnull', False)), fields=('local_filename',), name='server_rotations_api_rotationdistribution_distribution_local_filename_unique', violation_error_message='Название локального файла должно быть уникальным'),
        ),
        migrations.AddConstraint(
            model_name='rotationdistribution',
            constraint=models.UniqueConstraint(condition=models.Q(('url__isnull', False)), fields=('url',), name='server_rotations_api_rotationdistribution_distribution_url_unique', violation_error_message='Постфикс url должен быть уникальным'),
        ),
    ]
