# Generated by Django 4.2.11 on 2024-04-02 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_rotations_api', '0003_remove_rotationdistribution_distribution_local_filename_unique_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rotationdistribution',
            options={'ordering': ['rotation'], 'verbose_name': 'распространение ротации', 'verbose_name_plural': '1. Распространение ротаций'},
        ),
    ]
