# Generated by Django 4.2.14 on 2025-08-15 21:35

from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('server_rotations', '0005_alter_layerspack_creation_date_and_more'),
        ('server_rotations_api', '0004_alter_rotationdistribution_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotationdistribution',
            name='description',
            field=models.CharField(blank=True, help_text='Описание', max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='rotationdistribution',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активирована ли это конфигурация распространения', verbose_name='Активирован'),
        ),
        migrations.AlterField(
            model_name='rotationdistribution',
            name='last_queue_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='Последний номер набора с картами который был взят из ротации', verbose_name='Последний номер в очереди'),
        ),
        migrations.AlterField(
            model_name='rotationdistribution',
            name='last_update_date',
            field=models.DateTimeField(blank=True, help_text='Дата когда в последний раз изменялся номер в очереди', null=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='rotationdistribution',
            name='local_filename',
            field=models.CharField(blank=True, help_text='Название локального файла который будет создаваться в соответствующей папке. Доступны латинские буквы, цифры и знак подчеркивания (без множественных знаков подчеркивания подряд)', max_length=100, null=True, validators=[utils.filename_validator], verbose_name='Название локального файла'),
        ),
        migrations.AlterField(
            model_name='rotationdistribution',
            name='rotation',
            field=models.OneToOneField(help_text='Ротация из которой будет ежедневно браться новые карты', on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='server_rotations.rotation', verbose_name='Ротация'),
        ),
        migrations.AlterField(
            model_name='rotationdistribution',
            name='title',
            field=models.CharField(help_text='Название конфигурации распространения', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='rotationdistribution',
            name='type_of_distribution',
            field=models.CharField(choices=[('LOCAL', 'Локальный файл'), ('API', 'Через API'), ('API_LOCAL', 'Локальный файл и API')], default='LOCAL', help_text='Выберите какими путями будет распространятся конфигурация, файлом, через API (по ссылке) или комбинированно', max_length=10, verbose_name='Вариант распространения конфигурации'),
        ),
        migrations.AlterField(
            model_name='rotationdistribution',
            name='url',
            field=models.CharField(blank=True, help_text='Часть URL пути до этой конфигурации, просто любой удобный вам текст. Доступны латинские буквы, цифры и знак подчеркивания', max_length=100, null=True, validators=[utils.url_postfix_validator], verbose_name='Постфикс URL'),
        ),
    ]
