# Generated by Django 4.2.4 on 2023-12-12 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Краткое название')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'игровой режим',
                'verbose_name_plural': '5. Игровые режимы',
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название карты')),
                ('description', models.CharField(blank=True, max_length=511, verbose_name='Описание')),
                ('game_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server_rotations.gamemode', verbose_name='Игровой режим')),
            ],
            options={
                'verbose_name': 'карта',
                'verbose_name_plural': '3. Карты',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='LayerPackLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.PositiveSmallIntegerField(verbose_name='Номер в очереди')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_rotations.layer', verbose_name='карта')),
            ],
            options={
                'verbose_name': 'карта в паке',
                'verbose_name_plural': 'карты в паке',
                'ordering': ['queue_number'],
            },
        ),
        migrations.CreateModel(
            name='LayersPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активирован')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('layers', models.ManyToManyField(through='server_rotations.LayerPackLayer', to='server_rotations.layer', verbose_name='Список карт')),
            ],
            options={
                'verbose_name': 'пак с картами',
                'verbose_name_plural': '2. Паки с картами',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавление')),
            ],
            options={
                'verbose_name': 'ротация',
                'verbose_name_plural': '1. Ротации',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=50, verbose_name='Аббревиатура')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Полное название')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'команда',
                'verbose_name_plural': '4. Команды',
                'ordering': ['-abbreviation'],
            },
        ),
        migrations.CreateModel(
            name='RotationLayersPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('queue_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер в очереди')),
                ('start_date', models.DateField(blank=True, help_text='При выставлении этой даты - номер в очереди сбрасывается', null=True, verbose_name='Дата применения ротации')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_rotations.layerspack', verbose_name='пак с картами')),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs_through', to='server_rotations.rotation', verbose_name='ротация')),
            ],
            options={
                'verbose_name': 'пак с картами',
                'verbose_name_plural': 'паки с картами',
                'ordering': ['queue_number'],
            },
        ),
        migrations.AddField(
            model_name='rotation',
            name='packs',
            field=models.ManyToManyField(through='server_rotations.RotationLayersPack', to='server_rotations.layerspack', verbose_name='Наборы карт'),
        ),
        migrations.AddField(
            model_name='layerpacklayer',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers_through', to='server_rotations.layerspack', verbose_name='пак'),
        ),
        migrations.AddField(
            model_name='layer',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layer_team1', to='server_rotations.team', verbose_name='Команда 1'),
        ),
        migrations.AddField(
            model_name='layer',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layer_team2', to='server_rotations.team', verbose_name='Команда 2'),
        ),
        migrations.AddConstraint(
            model_name='rotationlayerspack',
            constraint=models.UniqueConstraint(condition=models.Q(('start_date__isnull', False)), fields=('rotation', 'start_date'), name='rotation_start_date_unique', violation_error_message='Дата начала должна быть уникальной'),
        ),
    ]
