# Generated by Django 4.2.4 on 2023-12-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_rotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rotationlayerspack',
            options={'ordering': [models.OrderBy(models.F('queue_number'), nulls_first=True), 'start_date'], 'verbose_name': 'пак с картами', 'verbose_name_plural': 'паки с картами'},
        ),
    ]
