# Generated by Django 4.2.14 on 2025-06-14 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_rotations', '0002_alter_rotationlayerspack_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='game_mode',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='layerpacklayer',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='layerpacklayer',
            name='pack',
        ),
        migrations.AlterModelOptions(
            name='layerspack',
            options={'ordering': ['-creation_date'], 'verbose_name': 'набор с картами', 'verbose_name_plural': '2. Наборы с картами'},
        ),
        migrations.RemoveField(
            model_name='layerspack',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='layerspack',
            name='layers',
        ),
        migrations.AlterField(
            model_name='rotationlayerspack',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_rotations.layerspack', verbose_name='Набор с картами'),
        ),
        migrations.DeleteModel(
            name='GameMode',
        ),
        migrations.DeleteModel(
            name='Layer',
        ),
        migrations.DeleteModel(
            name='LayerPackLayer',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AddField(
            model_name='layerspack',
            name='layers',
            field=models.TextField(blank=True, verbose_name='Лееры'),
        ),
    ]
