# Generated by Django 4.2.14 on 2025-06-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_rotations', '0003_remove_layer_game_mode_remove_layer_team1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rotationlayerspack',
            options={'ordering': [models.OrderBy(models.F('queue_number'), nulls_first=True), 'start_date'], 'verbose_name': 'набор с картами', 'verbose_name_plural': 'наборы с картами'},
        ),
    ]
