# Generated by Django 4.2.14 on 2025-08-15 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_rotations', '0004_alter_rotationlayerspack_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerspack',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата добавления наборка с картами', verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='layerspack',
            name='description',
            field=models.CharField(blank=True, help_text='Описание пака', max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='layerspack',
            name='layers',
            field=models.TextField(blank=True, help_text='Список карт, каждая карта (леер) с новой строки, поддерживаются комментарии с символа #', verbose_name='Список карт'),
        ),
        migrations.AlterField(
            model_name='layerspack',
            name='title',
            field=models.CharField(help_text='Название всего пака с картами', max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата добавления ротации', verbose_name='Дата добавление'),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='description',
            field=models.CharField(blank=True, help_text='Описание ротации', max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='packs',
            field=models.ManyToManyField(help_text='Список наборов карт по порядку', through='server_rotations.RotationLayersPack', to='server_rotations.layerspack', verbose_name='Наборы карт'),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='title',
            field=models.CharField(help_text='Название ротации (до 50 символов)', max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='rotationlayerspack',
            name='description',
            field=models.CharField(blank=True, help_text='Описание набора с картами именно в этой ротации', max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='rotationlayerspack',
            name='pack',
            field=models.ForeignKey(help_text='Набор с картами', on_delete=django.db.models.deletion.CASCADE, to='server_rotations.layerspack', verbose_name='Набор с картами'),
        ),
        migrations.AlterField(
            model_name='rotationlayerspack',
            name='queue_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Он лишь отражает очередность в списке и совсем не ему не обязательно идти подряд )', null=True, verbose_name='Номер в очереди'),
        ),
        migrations.AlterField(
            model_name='rotationlayerspack',
            name='rotation',
            field=models.ForeignKey(help_text='Ротация', on_delete=django.db.models.deletion.CASCADE, related_name='packs_through', to='server_rotations.rotation', verbose_name='ротация'),
        ),
    ]
