# Generated by Django 4.2.14 on 2025-08-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_rotations', '0005_alter_layerspack_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerspack',
            name='description',
            field=models.CharField(blank=True, help_text='Описание набора', max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='layerspack',
            name='title',
            field=models.CharField(help_text='Название всего набора с картами', max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
