# Generated by Django 4.2.14 on 2026-02-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_rotations', '0006_alter_layerspack_description_alter_layerspack_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rotationlayerspack',
            options={'verbose_name': 'набор с картами', 'verbose_name_plural': 'наборы с картами'},
        ),
        migrations.RemoveConstraint(
            model_name='rotationlayerspack',
            name='rotation_start_date_unique',
        ),
        migrations.AddField(
            model_name='rotationlayerspack',
            name='end_time_at',
            field=models.TimeField(blank=True, help_text='Дата и время когда в которое заканчивает отправляться данный набор карт', null=True, verbose_name='Время окончания применения набора карт'),
        ),
        migrations.AddField(
            model_name='rotationlayerspack',
            name='start_time_at',
            field=models.TimeField(blank=True, help_text='Дата и время в которое будет отправляться данный набор карт', null=True, verbose_name='Время начала применения набора карт'),
        ),
        migrations.AlterField(
            model_name='layerspack',
            name='layers',
            field=models.TextField(blank=True, help_text='Список карт, каждая карта (леер) с новой строки, поддерживаются комментарии с символа # или //', verbose_name='Список карт'),
        ),
        migrations.AlterField(
            model_name='rotationlayerspack',
            name='queue_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Он лишь отражает очередность в списке и ему совсем не обязательно идти подряд )', null=True, verbose_name='Номер в очереди'),
        ),
        migrations.AlterField(
            model_name='rotationlayerspack',
            name='start_date',
            field=models.DateField(blank=True, help_text='При выставлении этой даты - номер в очереди сбрасывается', null=True, verbose_name='Дата применения набора карт'),
        ),
    ]
