# Generated by Django 4.2.14 on 2026-02-14 12:23

import datetime

from django.db import migrations


def move_start_date_to_start_at_end_at(apps, schema_editor):
    model_rotation_layers_pack = apps.get_model("server_rotations", "RotationLayersPack")

    model_rotation_layers_pack.objects.filter(start_date__isnull=False).update(
        start_time_at=datetime.time.min, end_time_at=datetime.time.max
    )


class Migration(migrations.Migration):

    dependencies = [
        ("server_rotations", "0007_alter_rotationlayerspack_options_and_more"),
    ]

    operations = [
        migrations.RunPython(move_start_date_to_start_at_end_at, migrations.RunPython.noop),
    ]
