# Generated by Django 4.2.14 on 2026-02-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_rotations', '0008_move_start_date_to_start_at_end_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotationlayerspack',
            name='slug',
            field=models.SlugField(blank=True, help_text='Название для url или файла', max_length=255, null=True, verbose_name='Название для url или файла'),
        ),
        migrations.AddConstraint(
            model_name='rotationlayerspack',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__isnull', False)), fields=('slug', 'rotation'), name='rotation_layers_pack_unique_slug_and_rotation_when_slug_isnull_false'),
        ),
    ]
