[ADMIN_SITE]
ADMIN_SITE_HEADER = "Squad Admin Configurator"
ADMIN_SITE_TITLE = "Управление привилегированными пользователями"
ADMIN_INDEX_TITLE = "Squad Admin Configurator"

[SERVER]
BASE_URL = ""

[DJANGO]
SECRET_KEY = ""
DEBUG = true
ALLOWED_HOSTS = ['*']

[DISCORD]
[DISCORD.EXPIRED_PRIVILEGED_CHAT]
ENABLE = true
CHAT_WEBHOOK = ''

[ADMINS]
ADMINS_CONFIG_DIR = 'admins_configs'

[HMAC_VALIDATION]
[HMAC_VALIDATION.BATTLEMETRICS]
MAX_DEVIATION_OF_TIMESTAMP_IN_SEC = 10
