# Generated by Django 4.2.11 on 2024-04-02 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenproxy',
            options={'verbose_name': 'Токен', 'verbose_name_plural': '1. Токены'},
        ),
    ]
