version: '3.8'

services:
  db:
    image: postgres:15.4-bookworm
    volumes:
      - postgres_value:/var/lib/postgresql/data/
    env_file:
      - ./.env-dev
  squad-admin-configurator:
    build:
      dockerfile: ../squad-admin-configurator/Dockerfile.dev
      context: ../squad-admin-configurator/
    restart: always
    volumes:
      - ../squad-admin-configurator:/app
      - static_value:/app/static
      - ~/squad_admins_configs:/app/admins_configs
      - ~/squad_rotations_configs:/app/rotations_configs
    depends_on:
      - db
    env_file:
      - ./.env-dev
    ports:
      - "5678:5678"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static
    depends_on:
      - squad-admin-configurator

volumes:
  postgres_value:
  static_value:
