version: '3.8'

services:
  db:
    image: postgres:15.4-bookworm
    volumes:
      - postgres_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
  squad-admin-configurator:
    build: ../squad-admin-configurator
    restart: always
    volumes:
      - static_value:/squad-admin-configurator/static
      - ~/squad_admins_configs:/squad-admin-configurator/admins_configs
    depends_on:
      - db
    env_file:
      - ./.env
  migrations:
    build: ../squad-admin-configurator
    profiles: ["migrations"]
    restart: "no"
    entrypoint: ["bash", "-c", "python3 manage.py makemigrations; python3 manage.py migrate"]
    depends_on:
      - squad-admin-configurator
    env_file:
      - ./.env
  load-admins:
    build: ../squad-admin-configurator
    profiles: ["load-admins"]
    restart: "no"
    volumes:
      - ./Admins.cfg:/Admins.cfg
    entrypoint: ["bash", "-c", "python3 manage.py load_admin_config /Admins.cfg"]
    depends_on:
      - squad-admin-configurator
    env_file:
      - ./.env
  createsuperuser:
    build: ../squad-admin-configurator
    profiles: ["createsuperuser"]
    restart: "no"
    entrypoint: ["bash", "-c", "python3 manage.py createsuperuser"]
    depends_on:
      - squad-admin-configurator
    env_file:
      - ./.env
  nginx:
    image: nginx:alpine
    ports:
      - "1002:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static
    depends_on:
      - squad-admin-configurator

volumes:
  postgres_value:
  static_value:
