# Generated by Django 4.2.14 on 2025-08-15 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_cron_proxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronjoblog',
            options={'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
    ]
